language: python
matrix:
  include:
    - python: "3.6"
      env: UPLOAD=True
    - python: "3.6-dev"
    - python: "3.7-dev"

install:
    - pip install .[test] --process-dependency-links

script: pytest

deploy:
  provider: pypi
  distributions: sdist
  user: mara-pypi-upload-account
  password:
    secure: "NsXveyyvAh84sFZ8dKM110YnjAy9rUJqWP4VsCZB+agFPS+HECs2I3HJGmlL2iiORPyiB1OAIroLlzrCulioQHR6oEI/7t811qVwYmz+NRaCfATrwG4yt3ZsdI0vy8idwWgfsEzXMz5NN7ERT51qBfTou/5VNojn4gvFBCPh0DFfwEi/3vX/1K39h9CCJDjP5fGVmik31gB4WX4pNnaM0+PngB4UOYEo1CEFt0ERMaKs2lrGDVPk6VPO89SieOKDLXwoZGgV9nF1HSP+24cCrX9GqoTj/lKARxDcpyGXYGZXoC1G7P3hNUnEnbz9GAT2OQwjBVJELDJqg/KN9Zkw5vXBWE4liSQp1yYSBv7ssrcEM4pk3+0AZBGp3JY+uE2UxOU5+vfsAiu+RYQ7nlwIcwSUnZ1MeceUuGU6lnntgpzF5x++0FUEuB3E1gZFIHZWxv7oFBAFKYoqstNLzVkjsjsaVkLJLALqKnttVQL9lO6mrfq3kz/PW/fcBqc+ZF5qdkJvIiUO85mWwdS+AOSEaJNRcJyL6iD/nUjAMrW0/TftTu1SXU5bCRGB5wW/vE4hFJ38mpkcONxPNTSd0CKNq9+l5r0ym74m29H6et17r62grcFi5F3rlVN7t2kF1LXsPtWIW4squvrFl/NSFcw0QoRY+UXHmrOFagfoFjzQ4BA="
  on:
    tags: true
    branch: master
    repo: mara/mara-config
    condition: $UPLOAD == True

